# Dockerfile для разработки
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем исходный код
COPY . .

# Устанавливаем простой HTTP сервер для разработки
RUN npm install -g http-server

# Открываем порт 3000
EXPOSE 3000

# Запускаем простой HTTP сервер для Vanilla JS приложения из папки src
CMD ["http-server", "src", "-p", "3000", "-c-1", "--cors"]
