name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.version=${{ steps.get_version.outputs.VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Setup GitHub CLI
        uses: actions/setup-gh@v1

      - name: Create Release
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} \
            --title "Release ${{ steps.get_version.outputs.VERSION }}" \
            --notes "## What's Changed
            
          This release includes:
          - Docker image: \`ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}\`
          - Latest tag: \`ghcr.io/${{ github.repository }}:latest\`
          
          ## Docker Usage
          
          \`\`\`bash
          # Pull the specific version
          docker pull ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
          
          # Or use latest
          docker pull ghcr.io/${{ github.repository }}:latest
          \`\`\`
          
          ## Changelog
          
          See the [commit history](https://github.com/${{ github.repository }}/compare/...${{ github.ref }}) for detailed changes." \
            --draft=false \
            --prerelease=false

      - name: Notify release
        run: |
          echo "🎉 Release ${{ steps.get_version.outputs.VERSION }} created successfully!"
          echo "Docker image: ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}"
          echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}"
