name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## What's Changed
            
            This release includes:
            - Docker image: `ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}`
            - Latest tag: `ghcr.io/${{ github.repository }}:latest`
            
            ## Docker Usage
            
            ```bash
            # Pull the specific version
            docker pull ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            
            # Or use latest
            docker pull ghcr.io/${{ github.repository }}:latest
            ```
            
            ## Changelog
            
            See the [commit history](https://github.com/${{ github.repository }}/compare/...${{ github.ref }}) for detailed changes.
          draft: false
          prerelease: false

      - name: Update package.json version
        run: |
          npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git commit -m "Update version to ${{ steps.get_version.outputs.VERSION }}"
          git push

      - name: Notify release
        run: |
          echo "🎉 Release ${{ steps.get_version.outputs.VERSION }} created successfully!"
          echo "Docker image: ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}"
          echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}"
