name: Test and Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check available scripts
        id: check-scripts
        run: |
          if npm run | grep -q "lint"; then
            echo "lint-exists=true" >> $GITHUB_OUTPUT
          else
            echo "lint-exists=false" >> $GITHUB_OUTPUT
          fi
          
          if npm run | grep -q "test"; then
            echo "test-exists=true" >> $GITHUB_OUTPUT
          else
            echo "test-exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests
        if: steps.check-scripts.outputs.test-exists == 'true'
        run: npm test -- --watchAll=false --coverage
        continue-on-error: true

      - name: Skip tests
        if: steps.check-scripts.outputs.test-exists == 'false'
        run: echo "⚠️ No test script found in package.json. Skipping tests."

      - name: Run linting
        if: steps.check-scripts.outputs.lint-exists == 'true'
        run: npm run lint
        continue-on-error: true

      - name: Skip linting
        if: steps.check-scripts.outputs.lint-exists == 'false'
        run: echo "⚠️ No lint script found in package.json. Skipping linting."

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/
          retention-days: 7
