# Переменные окружения для GitHub Actions
# Этот файл содержит общие переменные для всех workflows

env:
  # Версия Node.js
  NODE_VERSION: '18'
  
  # Версия Docker
  DOCKER_VERSION: 'latest'
  
  # Регистр контейнеров
  REGISTRY: ghcr.io
  
  # Имя образа
  IMAGE_NAME: ${{ github.repository }}
  
  # Теги для Docker образа
  DOCKER_TAGS: |
    type=ref,event=branch
    type=ref,event=pr
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=sha,prefix={{branch}}-
    type=raw,value=latest,enable={{is_default_branch}}
  
  # Кэширование
  CACHE_FROM: type=gha
  CACHE_TO: type=gha,mode=max
  
  # Платформы для сборки
  PLATFORMS: linux/amd64,linux/arm64
